// modelInference.js
// Node.js module — Min-Max normalisation + Google AI Studio API inference
// Receives a raw feature object, normalises it using saved training
// parameters, submits to the Random Forest API, and returns a result.
 
'use strict';
 
const axios  = require('axios');
const scaler = require('./scaler.json');   // generated by post_test.py
 
const API_URL = process.env.GOOGLE_AI_STUDIO_ENDPOINT;
const API_KEY = process.env.GOOGLE_AI_API_KEY;
 
// Feature order must match training column order
const FEATURE_ORDER = [
  'FQDN_count', 'subdomain_length', 'upper', 'lower',
  'numeric', 'entropy', 'special', 'labels',
  'labels_max', 'labels_average', 'longest_word', 'len',
];
 
/**
 * Apply Min-Max normalisation to a feature object.
 * Formula: x_scaled = (x - min) / (max - min)
 *
 * @param  {Object} features  - Raw feature vector from extractFeatures()
 * @returns {Object}          - Normalised feature vector (values in [0,1])
 */
function normalise(features) {
  return Object.fromEntries(
    FEATURE_ORDER.map(key => {
      const raw = features[key] ?? 0;
      const { min, max } = scaler[key] || { min: 0, max: 1 };
      const scaled = (max === min) ? 0 : (raw - min) / (max - min);
      return [key, parseFloat(scaled.toFixed(6))];
    })
  );
}
 
/**
 * Submit a normalised feature vector to the deployed Random Forest model.
 *
 * @param  {Object} rawFeatures  - Output of extractFeatures()
 * @returns {Promise<Object>}    - { label, confidence, rawFeatures }
 *   label      : 'Benign' | 'Suspicious'
 *   confidence : string, e.g. '94.30'  (% of trees voting for predicted class)
 */
async function classifyRecord(rawFeatures) {
  const normFeatures = normalise(rawFeatures);
  const vector       = FEATURE_ORDER.map(k => normFeatures[k]);
 
  const response = await axios.post(
    API_URL,
    { instances: [vector] },
    {
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type':  'application/json',
      },
      timeout: 15000,
    }
  );
 
  const prediction = response.data.predictions[0];
  const maliciousProb = prediction.scores[1] ?? prediction.scores[0];
  const label         = maliciousProb >= 0.5 ? 'Suspicious' : 'Benign';
  const confidence    = (Math.max(...prediction.scores) * 100).toFixed(2);
 
  return { label, confidence, rawFeatures };
}
 
/**
 * Batch classify an array of feature objects.
 * Returns array of result objects preserving original order.
 *
 * @param  {Object[]} featureArray
 * @returns {Promise<Object[]>}
 */
async function classifyBatch(featureArray) {
  return Promise.all(featureArray.map(f => classifyRecord(f)));
}
 
module.exports = { classifyRecord, classifyBatch, normalise };
